spring:
  profiles:
    active: local  # 기본 프로필을 local로 지정
  config:
    import: optional:file:.env[.properties]
server:
  shutdown: graceful
  servlet:
    session:
      timeout: 0
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  batch:
    job:
      enabled: false  # 배치 자동 실행 방지
    jdbc:
      initialize-schema: never
fcm:
  config:
    path: firebase/firebase-config.json
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: push-notification-service
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fcm;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      password:
  batch:
    job:
      enabled: false  # 배치 자동 실행 방지
    jdbc:
      initialize-schema: always
fcm:
  config:
    path: firebase/firebase-config.json